### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by joxeankoret** [REhints/HexRaysCodeXplorer#12]
I haven't checked yet the source code but, do you think the plugin may support Linux?

**Comment by rrbranco** [comment]
not as is... but it will, soon ;)

**Comment by argp** [comment]
Excellent!

**Comment by matrosov** [comment]
In the next release we will try to add support for linux and OSX. Also thinking about switch on IdaPython for v2.0 ;) Thx for feedback guys!

**Comment by marc-etienne** [comment]
Hi guys,

I also want to make the plugin works on OS X. I have some time to work on porting CodeXplorer to Linux and OS X.

I'm seeing here you want to rewrite the whole thing in Python. Is that correct? Before I spend time on this, I would like your input on what I should spend time on:

 1. Modify existing code to make is compile (and work) on Linux and OS X
 2. Help you port the whole thing to Python
 3. Both

Option no 1 was my original idea, but if the correct code will not be used to future updates, It's kind of useless in the long term. Option no 2 involves a lot more work, and I don't think I have enough time to do it on my own. Do you already have some code done?

I don't think porting the exiting code to OS X and Linux would require much effort so I'll probably end up doing it anyway. Nonetheless, I just wanted your inputs before I start working on this.

Thanks!

**Comment by matrosov** [comment]
Hi Marc-Etienne,

Appreciate your help for porting CodeXplorer on on Linux and OS X. So currently porting CodeXplorer on python just started. I don't know when we are release the first version but I guess it will be not soon. Here is a lot of work because we should rewrite all things. Also we have some ideas to improve current core with some benefits of python. We are planning to support and include new features to C version in the next few upcoming releases.

The best option would be make a fork of current version. When you are finished make a pull request and we merge your contribution to main repository.  

Thanks!!

**Comment by mat0thew** [comment]
Plugin supporting IDA 6.7?
