### ISSUE TITLE
Which version should be used ?

### ISSUE THREAD

**Issue by trou** [REhints/HexRaysCodeXplorer#33]
Hello,
I'm a Linux user, I'd like to use the version you compiled for 6.95 but I'm quite confused by the labelling of versions : which one is the more recent ? Contest version ? Black Hat ?

Also, I tried to compile the current source code for IDA 6.95 but got crashes (or it didn't work after fixing th e NULL derefs). Are you using the code from github to compile the binaries ?

**Comment by matrosov** [comment]
Hi Raphaël ,

BlackHat version is specific build created for the talk in the last year (all the changes already migrated to main repo). All updates for CodeXplorer we push to the main repository. 

I currently more focusing on Win version because mostly use IDA on this OS. Do you interest for participate in the project to support Linux version of the plugin? I remember you already created first Linux version of the plugin in 2014. We also always open for new ideas ;)

Ping me on am@rehints.com if you are interested.

**Comment by trou** [comment]
So just to be sure, the build people should use is the one from the "Contest" dir ?

I can't really commit to supporting the Linux version because I'm not using it all the time, but I'll give a try at making current version work.

**Comment by trou** [comment]
Check PR #34

**Comment by matrosov** [comment]
The latest build placed at v2.0 [BlackHat Edition] directory. The contest dir exist for history about our participation in Hex-Rays contests.
