### ISSUE TITLE
 Use the same ida instance, open two different executable files, trigger a crash for the second time

### ISSUE THREAD

**Issue by x64bugreport** [REhints/HexRaysCodeXplorer#86]
ida version 7.5 sp2 in win10

Use the same ida instance, open two different executable files, and trigger a crash when the second program loads. The dump shows that the crash location is in ida.dll, which may be a memory corruption. Hope this bug will be repaired soon.

**Comment by x64bugreport** [comment]
The same ida instance triggers a null pointer exception when the executable file is loaded for the second time. It is determined that it is caused by the plug-in. Only the HexRaysCodeXplorer plug-in can still reproduce the

**Comment by x64bugreport** [comment]
![20201011093818](https://user-images.githubusercontent.com/34920463/95668398-17ff0e00-0ba6-11eb-9d44-19a882db51e6.jpg)

**Comment by x64bugreport** [comment]
Crash stack traceback
![20201011093818](https://user-images.githubusercontent.com/34920463/95668405-2f3dfb80-0ba6-11eb-9361-e0cb4a4d097d.jpg)

**Comment by x64bugreport** [comment]
Crash stack traceback
![20201011093818](https://user-images.githubusercontent.com/34920463/95668426-8774fd80-0ba6-11eb-8227-787c8463be56.jpg)
[Crash stack traceback](https://user-images.githubusercontent.com/34920463/95668426-8774fd80-0ba6-11eb-8227-787c8463be56.jpg)

**Comment by matrosov** [comment]
Thanks for reporting, I will check this issue.

**Comment by x64bugreport** [comment]
@matrosov 
This problem disappeared after modifying the plug-in initialization method, the reason is not very clear.
use this method PLUGIN_HIDE | PLUGIN_MULTI no crash.
crash from g_replace_id = register_place_class(&replace_template, /*flag == 0???*/PCF_EA_CAPABLE | PCF_MAKEPLACE_ALLOCATES/*0| PCF_EA_CAPABLE*/, &PLUGIN);

**Comment by Thealexbarney** [comment]
`PLUGIN_MULTI` doesn't fix the problem here.
And `register_place_class` isn't called a second time when opening a new database as the previous comment suggests.

**Comment by pr701** [comment]
After I checked the available versions of the app, the problem with IDA 7.5 was resolved.

The crash was related to the `register_place_class` fucntion.

On plugin unload, when closing its database, IDA should auntomatically unregister the element (`place_t`) as mentioned in documentaton: `In addition, the place_t will be automatically unregistered when the owner plugin is unloaded from memory.`
However, this fails. From what has been noticed, the corresponding function in ida64.dll is malformed (this is partially disassembled code).
![idadll](https://user-images.githubusercontent.com/82527127/124837236-20497580-df8d-11eb-9af7-47518cdc0d2d.png)
The condition fails due to the comparison against pointers to different elements.
![debug](https://user-images.githubusercontent.com/82527127/124837639-e331b300-df8d-11eb-8a2c-80b8634713c9.png)

After the plugin is unloaded, pointer values will not be deleted, so `register_place_class` called from any extension will initiate a search through pointers (`place_t`) in memory. Once it will try to dereferencing the pointer values, a call for the `name()` function will throw an access violation exception.
![place_vector](https://user-images.githubusercontent.com/82527127/124839826-3ad21d80-df92-11eb-8b65-2e42a32c09ac.png)

The solution is to update the plugin with PLUGIN_MULTI, as noted in `kernwin.hpp`:
`/// Deprecated, please update your plugins to use PLUGIN_MULTI.`
